name: Auto Squash & Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-squash-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if PR is from Dependabot and no conflicts
        run: |
          git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
          git status
          git diff --check

      - name: Auto Squash & Merge
        if: success() && github.actor == 'dependabot[bot]'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
